SERVER = "automationpractice.com"

STOREFRONT_URL = "http://"+SERVER+"/"
REGISTER_URL = "https://"+SERVER+"/index.php?controller=authentication&back=my-account#account-creation"
SHIPPING_URL = "http://"+SERVER+"/index.php?controller=order"
DELAY = "0.8"
TIMEOUT = "15"
NUMBER_2 = "2"
NUMBER_8 = "8"
user_email_part_2 = "@gmail.com"
